
networks:
  app-network:

services:
  java_app_api_rest:
    networks:
      - app-network
    container_name: java_app_api_rest
    image: api-rest-java_app:1.0.2
    build: .
    ports:
      - 8888:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db_2:13306/MYSQL_DATABASE  # Update port if needed
      - DATABASE_USERNAME=root  # Adjust if using a specific user
      - DATABASE_PASSWORD=docker  # Adjust password if needed
    depends_on:
      - java_db_2
  java_db_2:
    networks:
      - app-network
    container_name: java_db_2
    image: mysql:5.7  # Switch to MySQL image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker_data_base
    ports:
      - "13306:3306"  # Optional: Map host port 3306 to container port 3306
    volumes:
      - D:\TEST REPOSITORIES\docker_mysql\mysql-data:/var/lib/mysql




#version: "3.9"
#
#services:
##  #new app (angular_app)
##  angular_app:
##    container_name: angular_app
##    image: pee-angular_app:1.0.0
##    build: ./angular/my-front-app/
##    ports:
##      - 4200:4200
##    depends_on:
##      - java_app
#  java_app_api_rest:
#    container_name: java_app_api_rest
#    image: api-rest-java_app:1.0.2
#    build: .
#    ports:
#      - 8888:8080
#    environment:
#      - DATABASE_URL=jdbc:postgresql://java_db_2:5432/post21
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#    depends_on:
#      - java_db_2
#  java_db_2:
#    container_name: java_db_2
#    image: postgres:16
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: post21
