#spring.application.name=wiki


#Aplication configuration
server:
  port: 8091

#  to see the h2 console http://localhost:8091/h2-console
##===========================
## DB
##=============================

spring:
  application:
    name: "my-microservice"
  datasource:
    url: jdbc:h2:mem:productDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

h2:
  console:
    enabled: true
    path: /h2-console


#===========================
# JPA/HiBERNATE
#=============================
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
hibernate:
    show_sql: true
    use_sql_comments: false
    format_sql: false
logging:
  pattern:
    console:"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"





